/* 
 * 
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing InlineResponse400
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InlineResponse400Tests
    {
        // TODO uncomment below to declare an instance variable for InlineResponse400
        //private InlineResponse400 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InlineResponse400
            //instance = new InlineResponse400();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InlineResponse400
        /// </summary>
        [Test]
        public void InlineResponse400InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InlineResponse400
            //Assert.IsInstanceOfType<InlineResponse400> (instance, "variable 'instance' is a InlineResponse400");
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'ErrorDescription'
        /// </summary>
        [Test]
        public void ErrorDescriptionTest()
        {
            // TODO unit test for the property 'ErrorDescription'
        }

    }

}
